# Generated by Django 5.1.1 on 2024-10-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_nombre_alter_usuario_cod_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cod_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
