# Generated by Django 5.1.1 on 2024-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_cod_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dir_correo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nom_usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
